#!/usr/bin/env python
"""
    Usage:
        ./create_vpn_server --server-ip <IP>

    Options:
        <IP>        The IP address of the server you wish to set up
"""
from docopt import docopt


if __name__ == '__main__':
    args = docopt(__doc__)
